function grafice(R,C,f,val)

% Fereastra

figure('Name','Filtru RC Trece Sus',...
    'Units','normalized',...
    'Position',[0.05 0.05 0.7 0.85],...
    'NumberTitle','off');
set(gcf,'Color',[0 1 0]);

%Documentatie

f1=uimenu('Label','Documentatie');
uimenu(f1,'Label','Autor','Callback','open(''Autor.pdf'')');
uimenu(f1,'Label','Bibliografie','Callback','open(''Bibliografie.pdf'')');
uimenu(f1,'Label','Teorie','Callback','open(''Teorie.pdf'')');

  
% Chenare

Group1=uibuttongroup('BackgroundColor', [0.815 0.866 0.925],...
        'Title','Parametrii Circuitului',...
        'FontWeight','b',...
        'FontSize',13,...
        'Position',[0.75 0.5 0.2 0.38],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');
    
%Rezistenta

uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.25,0.80,0.5,0.08],...
          'BackgroundColor',[0.815 0.866 0.925],...
          'FontSize',12,...
          'FontWeight','b',...
          'String','Rezistenta R',...
          'Parent',Group1);

uicontrol('Style','Edit',...
    'Units','Normalized',...
    'Position',[0.25,0.70,0.5,0.08],...
    'FontSize',12,...
    'String',R,...
    'Callback',['R=','str2num(get(gco,''String'')),close,grafice(R,C,f,val)'],...
    'Parent',Group1);

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.75,0.70,0.2,0.08],...
    'BackgroundColor',[0.815 0.866 0.925],...
    'FontSize',12,...
    'FontWeight','b',...
    'String','[ohm]',...
    'Parent',Group1);
 
%Capacitatea 

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.25,0.50,0.5,0.08],...
    'BackgroundColor',[0.815 0.866 0.925],...
    'FontSize',12,...
    'FontWeight','b',...
    'String','Capacitatea C',...
    'Parent',Group1);

uicontrol('Style','Edit',...
    'Units','Normalized',...
    'Position',[0.25,0.40,0.5,0.08],...
    'FontSize',12,...
    'String',C,...
    'Callback',['C=','str2num(get(gco,''String'')),close,grafice(R,C,f,val)'],...
    'Parent',Group1);
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.75,0.40,0.2,0.08],...
    'BackgroundColor',[0.815 0.866 0.925],...
    'FontSize',12,...
    'FontWeight','b',...
    'String','[F]',...
    'Parent',Group1);

%Frecventa

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.25,0.20,0.5,0.08],...
    'BackgroundColor',[0.815 0.866 0.925],...
    'FontSize',12,...
    'FontWeight','b',...
    'String','Precizie',...
    'Parent',Group1);

uicontrol('Style','Edit',...
    'Units','Normalized',...
    'Position',[0.25,0.10,0.5,0.08],...
    'FontSize',12,...
    'String',f,...
    'Callback',['f=','str2num(get(gco,''String'')),close,grafice(R,C,f,val)'],...
    'Parent',Group1);
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.75,0.10,0.2,0.08],...
    'BackgroundColor',[0.815 0.866 0.925],...
    'FontSize',12,...
    'FontWeight','b',...
    'String','[Hz]',...
    'Parent',Group1);

Group2=uibuttongroup('Visible','on',...
        'BackgroundColor','[0.815 0.866 0.925]',...
        'ForegroundColor','black',...
        'Title','Calcule',...
        'FontSize',13,...
        'FontWeight','b',...
        'Position',[0.75 0.30 0.2 0.18],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');
    
%Calcule/Formule

f0=1./(2.*pi.*C.*R);
w0=2.*pi.*f0;
w=logspace(1,6,f);
f2=w/(2*pi);
num=R*C*w*j; 
den=R*C*w*j + 1;

h=abs(num./den);
gain=20*log10(h);
faza=angle(num./den)*180/pi;
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.10,0.7,0.8,0.2],...
          'BackgroundColor','[0.815 0.866 0.925]',...
          'FontSize',15,...
          'FontWeight','b',...
          'String',['f0 = ',num2str(f0),' Hz '],...
          'Parent',Group2);
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.10,0.3,0.8,0.2],...
          'BackgroundColor','[0.815 0.866 0.925]',...
          'FontSize',15,...
          'FontWeight','b',...
          'String',['w0 = ',num2str(w0),' Rad/s '],...
          'Parent',Group2);
      
%   grup afisare
GroupAfis=uibuttongroup('Visible','on',...
    'FontWeight', 'bold',...
    'Title','Semnal:',...
    'FontSize',10,...
    'BackgroundColor','[0.815 0.866 0.925]',...
    'TitlePosition','centertop',...
    'Position',[0.70 0.88 0.30 0.12]);
 % GRID
uicontrol('style','text',...
          'Units','normalized',...
          'String','Grid:',...
          'FontWeight', 'bold',...
          'Position',[0.05 0.05 0.5 0.4],...
          'BackgroundColor','[0.815 0.866 0.925]',...
          'Parent',GroupAfis);
 
    RadioB1=uicontrol('style','radiobutton',...
          'Units','normalized',...
          'String','ON',...
          'FontWeight', 'bold',...
          'Position',[0.55 0.25 0.2 0.2],...
          'Parent',GroupAfis,...
          'BackgroundColor','[0.815 0.866 0.925]',...
          'Callback','val=1,close;grafice(R,C,f,val);');
      
      RadioB2=uicontrol('style','radiobutton',...
          'Units','normalized',...
          'String','OFF',...
          'FontWeight', 'bold',...
          'Position',[0.75 0.25 0.2 0.2],...
          'BackgroundColor','[0.815 0.866 0.925]',...
          'Parent',GroupAfis,...
          'Callback','val=2,close;grafice(R,C,f,val);');


 
  %Grafice
  subplot('Position', [0.1 0.72 0.6 0.23]);
  semilogx(f2,h,'g-',f0,1./sqrt(2),'o', 'LineWidth',3);
    grid on;
  xlabel('Frecventa [ Hz ]');
  ylabel('|H(jw)| ');
  title('Caracteristica  |H(jw)|','Fontweight','b');
  legend(' |U2 / U1 |');
  if val == 1
set(RadioB1,'value',1)
set(RadioB2,'value',0)
grid on;
else
set(RadioB1,'value',0)
set(RadioB2,'value',1)
grid off;
end
  
  subplot('Position', [0.1 0.40 0.6 0.23]);
  semilogx(f2,gain,'r-',f0,-3,'o','LineWidth',3);
    grid on;
  xlabel('Frecventa [ Hz ]');
  ylabel('Castigul [ dB ]');
  title('Castigul','fontweight','b');
  legend('Castigul')
  if val == 1
set(RadioB1,'value',1)
set(RadioB2,'value',0)
grid on;
else
set(RadioB1,'value',0)
set(RadioB2,'value',1)
grid off;
end
  
 subplot('Position', [0.1 0.08 0.6 0.23]);
 semilogx(f2,faza,'b-',f0,+45,'o','LineWidth',3);
 grid on;
 xlabel('Frecventa [ Hz ]');
 ylabel('Faza [ radiani ]');
 title('Faza semnalului','Fontweight','b');
 legend('Faza');
 if val == 1
set(RadioB1,'value',1)
set(RadioB2,'value',0)
grid on;
else
set(RadioB1,'value',0)
set(RadioB2,'value',1)
grid off;
end
 
 %Iesire
uicontrol('Style','pushbutton', ...
     'Units','normalized', ...
     'Position',[0.80 0.1 0.10 0.06], ...
     'BackgroundColor','[0.815 0.866 0.925]',...
     'String','Iesire', ...
     'FontName','Times New Roman',...
     'FontSize',19,... 
     'FontWeight','Bold',...
     'Callback','close;');
 uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.8 0.02 0.10 0.06],...
          'string','Inapoi',...
          'FontName','Times New Roman',...
          'backgroundcolor',[0.815 0.866 0.925],...
          'FontSize',19,... 
          'FontWeight','Bold',...
          'Callback','main_page');

    

end
