function interfata_fts
 
figure('Name','Proiect Filtru RC Trece sus',... %---Numele ferestrei---%
 'Units','normalized',...%---Unitatile de masura  0->1-%
 'Position',[0.1 0.07 0.7 0.83],...%---Pozitia ferestrei pe ecran
 'NumberTitle','off'); %---Numarul ferestrei - nu se atribuie---%
set(gcf, 'Color',[0 1 0]);

%----------Titlu-----------------------------%
   uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.25 0.82 0.5 0.08],...
        'backgroundcolor',[0.815 0.866 0.925],...',...
        'foregroundcolor','black',...
        'Fontname','Times New Roman',...
        'FontWeight','Bold',...
        'FontSize',26,...
        'String','Circuit RC Filtru Trece Sus');
 
 %---------------Citire imagine Filtru RC Trece Sus----------%
 uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.35 0.73 0.3 0.05],...
        'backgroundcolor',[0.815 0.866 0.925],...
        'foregroundcolor','black',...
        'FontWeight','Bold',...
        'Fontname','Times New Roman',...
        'FontSize',18,...
        'String','Schema circuitului'); 
 subplot('position',[0.15 0.20 0.7 0.5])
 z = imread('fts.png');
 image(z); 
 axis off;
 
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.7 0.05 0.205 0.1],...
          'string','Inapoi',...
          'FontName','Times New Roman',...
          'backgroundcolor',[0.815 0.866 0.925],...
          'FontSize',19,... 
          'FontWeight','Bold',...
          'Callback','main_page');


end
