%-------------------- Crearea figurii INTERFATA ---------------------------

Fig = figure('Name', 'Proiect Grafica', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.1 0.8 0.7], ...
             'NumberTitle', 'off');
set(gcf, 'Color', [0.768 0.811 0.737]);

ah = axes('unit', 'normalized', 'position', [0 0 1 1]);
bg = imread('imagine_main.jpg'); 
imagesc(bg);
set(ah, 'handlevisibility', 'off', 'visible', 'off');

%----------Titlu (mijloc jos)----------------------------------------%
uicontrol('Style', 'text', ...
          'Units', 'normalized', ...
          'Position', [0.3 0.25 0.4 0.15], ...
          'foregroundcolor', 'k', ...
          'backgroundcolor', [1 1 1], ...
          'Fontname', 'Times New Roman', ...
          'FontWeight', 'Bold', ...
          'FontSize', 32, ...
          'String', 'Circuit RC Filtru Trece Sus');

%---------------Grup de meniuri----------%
m = uimenu('Label', 'Documentatie Proiect');
uimenu(m, 'Label', 'Autor', 'Callback', 'open(''Autor.pdf'')');
uimenu(m, 'Label', 'Teorie', 'Callback', 'open(''teorie.pdf'')');
uimenu(m, 'Label', 'Bibliografie', 'Callback', 'open(''Bibliografie.pdf'')');
uimenu(m, 'Label', 'Close', 'Callback', 'close', 'Separator', 'on', 'Accelerator', 'Q');

%-------------------- Crearea Butoanelor ----------------------------------

% Butonul Schema Filtru (sus)
uicontrol('style', 'pushbutton', ...
          'Units', 'normalized', ...
          'Position', [0.04 0.8 0.2 0.11], ...
          'string', 'Schema Filtru', ...
          'FontName', 'Times New Roman', ...
          'FontSize', 15, ...
          'Foregroundcolor', 'k', ...
          'Backgroundcolor', [1 1 1], ...
          'FontWeight', 'Bold', ...
          'Callback', 'interfata_fts');

% Butonul Grafice Filtru (sus)
uicontrol('style', 'pushbutton', ...
          'Units', 'normalized', ...
          'Position', [0.28 0.8 0.2 0.11], ...
          'string', 'Grafice Filtru', ...
          'FontName', 'Times New Roman', ...
          'FontSize', 17, ...
          'foregroundcolor', 'k', ...
          'FontWeight', 'Bold', ...
          'backgroundcolor', [1 1 1], ...
          'Callback', 'start');

% Butonul Prezentare PPT
uicontrol('style', 'pushbutton', ...
          'Units', 'normalized', ...
          'Position', [0.52 0.8 0.2 0.11], ...
          'string', 'Prezentare', ...
          'FontName', 'Times New Roman', ...
          'FontSize', 17, ...
          'foregroundcolor', 'k', ...
          'FontWeight', 'Bold', ...
          'backgroundcolor', [1 1 1], ...
          'Callback','open (''Prezentare.pdf'')');


% Butonul Inchide (sus)
uicontrol('style', 'pushbutton', ...
          'Units', 'normalized', ...
          'Position', [0.76 0.8 0.2 0.11], ...
          'string', 'Inchide', ...
          'FontName', 'Times New Roman', ...
          'FontSize', 15, ...
          'foregroundcolor', 'k', ...
          'backgroundcolor', [1 1 1], ...
          'FontWeight', 'Bold', ...
          'Callback', 'close;');
